name: "Deploy CDK Stacks"
description: "Configure AWS credentials and deploy CDK stacks"

inputs:
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  aws-region:
    description: "AWS Region"
    required: false
    default: "us-east-2"
  environment:
    description: "Deployment environment (dev, stage, prod)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Clean old CDK assets
      shell: bash
      run: |
        CDK_ASSETS_BUCKET=$(aws s3api list-buckets --query 'Buckets[?contains(Name, `cdk-`) && contains(Name, `-assets-`)].Name' --output text | head -1)
        if [ -n "$CDK_ASSETS_BUCKET" ]; then
          echo "Cleaning CDK assets bucket: $CDK_ASSETS_BUCKET"
          aws s3 rm s3://$CDK_ASSETS_BUCKET/ --recursive
        else
          echo "No CDK assets bucket found"
        fi

    - name: Deploy Main Stack
      shell: bash
      run: npm run cdk:deploy -- --require-approval never
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id  }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key  }}
        AWS_REGION: ${{ inputs.aws-region }}
