/**
 * Project context detection utilities
 *
 * Detects whether commands are run from inside a valid project directory
 * by searching upward for .aws-starter-config.json
 */

import { findUp } from 'find-up';
import { readFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import pc from 'picocolors';

/**
 * Config file name that marks a project directory
 * This file is generated by the wizard and contains project settings
 */
export const CONFIG_FILE = '.aws-starter-config.json';

/**
 * Minimal project config structure for context detection
 * Full config defined in types.ts - this is subset needed for context
 */
export interface ProjectConfigMinimal {
  projectName: string;
  platforms: string[];
  awsRegion: string;
  configVersion?: string;
}

/**
 * Project context containing config path, project root, and parsed config
 */
export interface ProjectContext {
  configPath: string;
  projectRoot: string;
  config: ProjectConfigMinimal;
}

/**
 * Detects if running from inside a valid project directory
 * Searches upward from cwd for CONFIG_FILE
 *
 * @returns ProjectContext if found, null otherwise
 */
export async function detectProjectContext(): Promise<ProjectContext | null> {
  const configPath = await findUp(CONFIG_FILE);

  if (!configPath) {
    return null;
  }

  try {
    const content = await readFile(configPath, 'utf-8');
    const config = JSON.parse(content) as ProjectConfigMinimal;

    // Basic validation - config must have projectName
    if (!config.projectName) {
      return null;
    }

    return {
      configPath,
      projectRoot: dirname(configPath),
      config,
    };
  } catch {
    // Invalid JSON or read error - treat as no context
    return null;
  }
}

/**
 * Requires project context, exits with error if not found
 * Use this for commands that must run from inside a project
 *
 * @returns ProjectContext (never returns null, exits on failure)
 */
export async function requireProjectContext(): Promise<ProjectContext> {
  const context = await detectProjectContext();

  if (!context) {
    console.error(pc.red('Error:') + ' Not inside a project directory.');
    console.error('');
    console.error('This command must be run from inside a project created with:');
    console.error(`  ${pc.cyan('npx create-aws-project <project-name>')}`);
    console.error('');
    console.error(`Expected config file: ${pc.cyan(CONFIG_FILE)}`);
    process.exit(1);
  }

  return context;
}
